/**
 * Colorado counties with population and region data
 * Starting with Denver metro area pilot counties
 */
export const COLORADO_COUNTIES = [
  { name: "Adams", population: 519572, region: "Denver Metro" },
  { name: "Alamosa", population: 16233, region: "San Luis Valley" },
  { name: "Arapahoe", population: 656590, region: "Denver Metro" },
  { name: "Archuleta", population: 14029, region: "Southwest" },
  { name: "Baca", population: 3347, region: "Southeast" },
  { name: "Bent", population: 5577, region: "Southeast" },
  { name: "Boulder", population: 330758, region: "Front Range" },
  { name: "Broomfield", population: 74112, region: "Denver Metro" },
  { name: "Chaffee", population: 20356, region: "Central Mountain" },
  { name: "Cheyenne", population: 1831, region: "Eastern Plains" },
  { name: "Clear Creek", population: 9700, region: "Central Mountain" },
  { name: "Conejos", population: 7971, region: "San Luis Valley" },
  { name: "Costilla", population: 3887, region: "San Luis Valley" },
  { name: "Crowley", population: 6061, region: "Southeast" },
  { name: "Custer", population: 5068, region: "Central Mountain" },
  { name: "Delta", population: 31258, region: "Western Slope" },
  { name: "Denver", population: 715522, region: "Denver Metro" },
  { name: "Dolores", population: 2055, region: "Southwest" },
  { name: "Douglas", population: 357978, region: "Denver Metro" },
  { name: "Eagle", population: 55127, region: "Central Mountain" },
  { name: "El Paso", population: 730395, region: "Pikes Peak" },
  { name: "Elbert", population: 27921, region: "Eastern Plains" },
  { name: "Fremont", population: 48942, region: "Central Mountain" },
  { name: "Garfield", population: 60061, region: "Western Slope" },
  { name: "Gilpin", population: 6243, region: "Central Mountain" },
  { name: "Grand", population: 15734, region: "Central Mountain" },
  { name: "Gunnison", population: 17462, region: "Western Slope" },
  { name: "Hinsdale", population: 820, region: "Southwest" },
  { name: "Huerfano", population: 6897, region: "South Central" },
  { name: "Jackson", population: 1392, region: "North Central" },
  { name: "Jefferson", population: 582881, region: "Denver Metro" },
  { name: "Kiowa", population: 1406, region: "Eastern Plains" },
  { name: "Kit Carson", population: 7097, region: "Eastern Plains" },
  { name: "La Plata", population: 56221, region: "Southwest" },
  { name: "Lake", population: 8091, region: "Central Mountain" },
  { name: "Larimer", population: 359066, region: "Front Range" },
  { name: "Las Animas", population: 14506, region: "Southeast" },
  { name: "Lincoln", population: 5701, region: "Eastern Plains" },
  { name: "Logan", population: 22409, region: "Eastern Plains" },
  { name: "Mesa", population: 154210, region: "Western Slope" },
  { name: "Mineral", population: 769, region: "San Luis Valley" },
  { name: "Moffat", population: 13283, region: "Northwest" },
  { name: "Montezuma", population: 26266, region: "Southwest" },
  { name: "Montrose", population: 47170, region: "Western Slope" },
  { name: "Morgan", population: 29068, region: "Eastern Plains" },
  { name: "Otero", population: 18278, region: "Southeast" },
  { name: "Ouray", population: 4952, region: "Southwest" },
  { name: "Park", population: 18845, region: "Central Mountain" },
  { name: "Phillips", population: 4282, region: "Eastern Plains" },
  { name: "Pitkin", population: 17767, region: "Central Mountain" },
  { name: "Prowers", population: 11841, region: "Southeast" },
  { name: "Pueblo", population: 168424, region: "Pikes Peak" },
  { name: "Rio Blanco", population: 6324, region: "Northwest" },
  { name: "Rio Grande", population: 11267, region: "San Luis Valley" },
  { name: "Routt", population: 25638, region: "Northwest" },
  { name: "Saguache", population: 6824, region: "San Luis Valley" },
  { name: "San Juan", population: 728, region: "Southwest" },
  { name: "San Miguel", population: 8179, region: "Southwest" },
  { name: "Sedgwick", population: 2248, region: "Eastern Plains" },
  { name: "Summit", population: 31011, region: "Central Mountain" },
  { name: "Teller", population: 25388, region: "Pikes Peak" },
  { name: "Washington", population: 4814, region: "Eastern Plains" },
  { name: "Weld", population: 328981, region: "Front Range" },
  { name: "Yuma", population: 10019, region: "Eastern Plains" }
];

export default COLORADO_COUNTIES;
