/**
 * Data loading utilities for DaycareWatch
 * Handles loading facility data from JSON files generated by scrapers
 */

// Re-export counties from state configs for backward compatibility
export { CALIFORNIA_COUNTIES } from '../states/california/counties';

/**
 * Convert county name to filename format
 */
export const countyToFilename = (countyName) => {
  return countyName.toLowerCase().replace(/ /g, '_');
};

/**
 * Load facility data for a specific county
 * @param {string} stateId - State identifier (e.g., 'california', 'minnesota')
 * @param {string} countyName - Name of the county
 * @returns {Promise<Array>} Array of facility objects
 */
export const loadCountyData = async (stateId, countyName) => {
  try {
    const filename = countyToFilename(countyName);
    const response = await fetch(`/data/${stateId}/${filename}_facilities.json`);

    if (!response.ok) {
      console.warn(`No data file found for ${countyName}, ${stateId}`);
      return null;
    }

    return await response.json();
  } catch (error) {
    console.error(`Error loading data for ${countyName}, ${stateId}:`, error);
    return null;
  }
};

/**
 * Load summary data for a state
 * @param {string} stateId - State identifier (e.g., 'california', 'minnesota')
 * @returns {Promise<Object>} Summary object
 */
export const loadSummary = async (stateId) => {
  try {
    const response = await fetch(`/data/${stateId}/summary.json`);

    if (!response.ok) {
      return null;
    }

    return await response.json();
  } catch (error) {
    console.error(`Error loading summary for ${stateId}:`, error);
    return null;
  }
};

/**
 * Calculate statistics for a set of facilities
 * @param {Array} facilities - Array of facility objects
 * @returns {Object} Statistics object
 */
export const calculateStats = (facilities) => {
  if (!facilities || facilities.length === 0) {
    return {
      totalFacilities: 0,
      totalCapacity: 0,
      byType: {},
      byStatus: {},
      avgCapacity: 0,
      flaggedCount: 0
    };
  }

  const stats = {
    totalFacilities: facilities.length,
    totalCapacity: 0,
    byType: {},
    byStatus: {},
    avgCapacity: 0,
    flaggedCount: 0,
    withViolations: 0,
    recentlyInspected: 0
  };

  const now = new Date();
  const sixMonthsAgo = new Date(now.setMonth(now.getMonth() - 6));

  facilities.forEach(facility => {
    // Sum capacity
    stats.totalCapacity += facility.capacity || 0;

    // Count by type
    const type = facility.facility_type || 'Unknown';
    stats.byType[type] = (stats.byType[type] || 0) + 1;

    // Count by status
    const status = facility.status || 'Unknown';
    stats.byStatus[status] = (stats.byStatus[status] || 0) + 1;

    // Count facilities with violations
    if (facility.total_citations > 0) {
      stats.withViolations++;
    }

    // Count recently inspected
    if (facility.last_inspection_date) {
      const inspectionDate = new Date(facility.last_inspection_date);
      if (inspectionDate >= sixMonthsAgo) {
        stats.recentlyInspected++;
      }
    }

    // Check if flagged (based on various criteria)
    if (isFlagged(facility)) {
      stats.flaggedCount++;
    }
  });

  stats.avgCapacity = Math.round(stats.totalCapacity / stats.totalFacilities);

  return stats;
};

/**
 * Determine if a facility should be flagged for review
 * @param {Object} facility - Facility object
 * @returns {boolean} Whether facility is flagged
 */
export const isFlagged = (facility) => {
  const flags = getFlagReasons(facility);
  return flags.length > 0;
};

/**
 * Get reasons why a facility is flagged
 * @param {Object} facility - Facility object
 * @returns {Array<string>} Array of flag reasons
 */
export const getFlagReasons = (facility) => {
  const reasons = [];

  // High violation count
  if (facility.total_citations >= 5) {
    reasons.push(`High citation count: ${facility.total_citations}`);
  }

  // No recent inspection
  if (facility.last_inspection_date) {
    const lastInspection = new Date(facility.last_inspection_date);
    const sixMonthsAgo = new Date();
    sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);
    
    if (lastInspection < sixMonthsAgo) {
      reasons.push('No inspection in 6+ months');
    }
  }

  // High capacity with limited inspection history
  if (facility.capacity > 50 && (!facility.total_visits || facility.total_visits < 2)) {
    reasons.push('High capacity facility with limited inspection history');
  }

  // Future: Add payment-based flags when subsidy data available
  // if (facility.subsidyPayments && facility.capacity) {
  //   const paymentPerSlot = facility.subsidyPayments / facility.capacity;
  //   if (paymentPerSlot > THRESHOLD) {
  //     reasons.push('Unusually high payment per capacity slot');
  //   }
  // }

  return reasons;
};

/**
 * Search facilities by name or address
 * @param {Array} facilities - Array of facility objects
 * @param {string} query - Search query
 * @returns {Array} Filtered facilities
 */
export const searchFacilities = (facilities, query) => {
  if (!query || query.trim() === '') {
    return facilities;
  }

  const lowerQuery = query.toLowerCase();
  
  return facilities.filter(facility => {
    return (
      (facility.name && facility.name.toLowerCase().includes(lowerQuery)) ||
      (facility.address && facility.address.toLowerCase().includes(lowerQuery)) ||
      (facility.city && facility.city.toLowerCase().includes(lowerQuery)) ||
      (facility.license_number && facility.license_number.includes(query))
    );
  });
};

/**
 * Filter facilities by various criteria
 * @param {Array} facilities - Array of facility objects
 * @param {Object} filters - Filter criteria
 * @returns {Array} Filtered facilities
 */
export const filterFacilities = (facilities, filters = {}) => {
  let filtered = [...facilities];

  if (filters.type) {
    filtered = filtered.filter(f => f.facility_type === filters.type);
  }

  if (filters.status) {
    filtered = filtered.filter(f => f.status === filters.status);
  }

  if (filters.flaggedOnly) {
    filtered = filtered.filter(f => isFlagged(f));
  }

  if (filters.minCapacity) {
    filtered = filtered.filter(f => f.capacity >= filters.minCapacity);
  }

  if (filters.maxCapacity) {
    filtered = filtered.filter(f => f.capacity <= filters.maxCapacity);
  }

  if (filters.hasViolations) {
    filtered = filtered.filter(f => f.total_citations > 0);
  }

  return filtered;
};

/**
 * Sort facilities by a given field
 * @param {Array} facilities - Array of facility objects
 * @param {string} field - Field to sort by
 * @param {string} direction - 'asc' or 'desc'
 * @returns {Array} Sorted facilities
 */
export const sortFacilities = (facilities, field = 'name', direction = 'asc') => {
  return [...facilities].sort((a, b) => {
    let aVal = a[field];
    let bVal = b[field];

    // Handle nulls
    if (aVal === null || aVal === undefined) aVal = '';
    if (bVal === null || bVal === undefined) bVal = '';

    // Numeric comparison for numbers
    if (typeof aVal === 'number' && typeof bVal === 'number') {
      return direction === 'asc' ? aVal - bVal : bVal - aVal;
    }

    // String comparison
    aVal = String(aVal).toLowerCase();
    bVal = String(bVal).toLowerCase();

    if (direction === 'asc') {
      return aVal.localeCompare(bVal);
    }
    return bVal.localeCompare(aVal);
  });
};

/**
 * Export facilities to CSV
 * @param {Array} facilities - Array of facility objects
 * @returns {string} CSV content
 */
export const exportToCSV = (facilities) => {
  const headers = [
    'License Number',
    'Name',
    'Type',
    'Address',
    'City',
    'Zip',
    'Capacity',
    'Status',
    'Last Inspection',
    'Citations',
    'CCLD URL'
  ];

  const rows = facilities.map(f => [
    f.license_number,
    `"${(f.name || '').replace(/"/g, '""')}"`,
    f.facility_type,
    `"${(f.address || '').replace(/"/g, '""')}"`,
    f.city,
    f.zip_code,
    f.capacity,
    f.status,
    f.last_inspection_date || '',
    f.total_citations || 0,
    f.ccld_url
  ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
};

export default {
  countyToFilename,
  loadCountyData,
  loadSummary,
  calculateStats,
  isFlagged,
  getFlagReasons,
  searchFacilities,
  filterFacilities,
  sortFacilities,
  exportToCSV
};
