/**
 * California counties with population and region data
 */
export const CALIFORNIA_COUNTIES = [
  { name: "Alameda", population: 1682353, region: "Bay Area" },
  { name: "Alpine", population: 1204, region: "Sierra Nevada" },
  { name: "Amador", population: 40474, region: "Central Sierra" },
  { name: "Butte", population: 211632, region: "North Valley" },
  { name: "Calaveras", population: 45292, region: "Central Sierra" },
  { name: "Colusa", population: 21917, region: "North Valley" },
  { name: "Contra Costa", population: 1165927, region: "Bay Area" },
  { name: "Del Norte", population: 27743, region: "North Coast" },
  { name: "El Dorado", population: 193221, region: "Central Sierra" },
  { name: "Fresno", population: 1008654, region: "Central Valley" },
  { name: "Glenn", population: 28917, region: "North Valley" },
  { name: "Humboldt", population: 136310, region: "North Coast" },
  { name: "Imperial", population: 179702, region: "Southern Border" },
  { name: "Inyo", population: 19016, region: "Eastern Sierra" },
  { name: "Kern", population: 909235, region: "Central Valley" },
  { name: "Kings", population: 153443, region: "Central Valley" },
  { name: "Lake", population: 68163, region: "North Coast" },
  { name: "Lassen", population: 32730, region: "Northeast" },
  { name: "Los Angeles", population: 9829544, region: "Southern California" },
  { name: "Madera", population: 160089, region: "Central Valley" },
  { name: "Marin", population: 262321, region: "Bay Area" },
  { name: "Mariposa", population: 17131, region: "Central Sierra" },
  { name: "Mendocino", population: 91305, region: "North Coast" },
  { name: "Merced", population: 286461, region: "Central Valley" },
  { name: "Modoc", population: 8700, region: "Northeast" },
  { name: "Mono", population: 13195, region: "Eastern Sierra" },
  { name: "Monterey", population: 439035, region: "Central Coast" },
  { name: "Napa", population: 138019, region: "Bay Area" },
  { name: "Nevada", population: 102241, region: "Central Sierra" },
  { name: "Orange", population: 3186989, region: "Southern California" },
  { name: "Placer", population: 412300, region: "Central Sierra" },
  { name: "Plumas", population: 19790, region: "Northeast" },
  { name: "Riverside", population: 2458395, region: "Southern California" },
  { name: "Sacramento", population: 1585055, region: "Capital Region" },
  { name: "San Benito", population: 66677, region: "Central Coast" },
  { name: "San Bernardino", population: 2194710, region: "Southern California" },
  { name: "San Diego", population: 3298634, region: "Southern Border" },
  { name: "San Francisco", population: 873965, region: "Bay Area" },
  { name: "San Joaquin", population: 789410, region: "Central Valley" },
  { name: "San Luis Obispo", population: 283111, region: "Central Coast" },
  { name: "San Mateo", population: 764442, region: "Bay Area" },
  { name: "Santa Barbara", population: 446527, region: "Central Coast" },
  { name: "Santa Clara", population: 1936259, region: "Bay Area" },
  { name: "Santa Cruz", population: 267792, region: "Central Coast" },
  { name: "Shasta", population: 182155, region: "North Valley" },
  { name: "Sierra", population: 3236, region: "Northeast" },
  { name: "Siskiyou", population: 44076, region: "Northeast" },
  { name: "Solano", population: 453491, region: "Bay Area" },
  { name: "Sonoma", population: 488863, region: "Bay Area" },
  { name: "Stanislaus", population: 552999, region: "Central Valley" },
  { name: "Sutter", population: 99063, region: "North Valley" },
  { name: "Tehama", population: 65829, region: "North Valley" },
  { name: "Trinity", population: 16060, region: "North Coast" },
  { name: "Tulare", population: 477054, region: "Central Valley" },
  { name: "Tuolumne", population: 55620, region: "Central Sierra" },
  { name: "Ventura", population: 843843, region: "Southern California" },
  { name: "Yolo", population: 216403, region: "Capital Region" },
  { name: "Yuba", population: 81575, region: "North Valley" }
];

export default CALIFORNIA_COUNTIES;
