/**
 * Minnesota counties with population, region, and county seat data
 * 87 counties total
 */
export const MINNESOTA_COUNTIES = [
  { name: "Aitkin", population: 15886, region: "Central", countySeat: "Aitkin" },
  { name: "Anoka", population: 363887, region: "Twin Cities Metro", countySeat: "Anoka" },
  { name: "Becker", population: 34767, region: "West Central", countySeat: "Detroit Lakes" },
  { name: "Beltrami", population: 47188, region: "Northwest", countySeat: "Bemidji" },
  { name: "Benton", population: 41379, region: "Central", countySeat: "Foley" },
  { name: "Big Stone", population: 4991, region: "West Central", countySeat: "Ortonville" },
  { name: "Blue Earth", population: 67653, region: "South Central", countySeat: "Mankato" },
  { name: "Brown", population: 25008, region: "South Central", countySeat: "New Ulm" },
  { name: "Carlton", population: 35871, region: "Northeast", countySeat: "Carlton" },
  { name: "Carver", population: 106922, region: "Twin Cities Metro", countySeat: "Chaska" },
  { name: "Cass", population: 29779, region: "Central", countySeat: "Walker" },
  { name: "Chippewa", population: 11629, region: "West Central", countySeat: "Montevideo" },
  { name: "Chisago", population: 56543, region: "Twin Cities Metro", countySeat: "Center City" },
  { name: "Clay", population: 64222, region: "West Central", countySeat: "Moorhead" },
  { name: "Clearwater", population: 8818, region: "Northwest", countySeat: "Bagley" },
  { name: "Cook", population: 5463, region: "Northeast", countySeat: "Grand Marais" },
  { name: "Cottonwood", population: 11196, region: "Southwest", countySeat: "Windom" },
  { name: "Crow Wing", population: 65055, region: "Central", countySeat: "Brainerd" },
  { name: "Dakota", population: 439882, region: "Twin Cities Metro", countySeat: "Hastings" },
  { name: "Dodge", population: 20867, region: "Southeast", countySeat: "Mantorville" },
  { name: "Douglas", population: 38141, region: "West Central", countySeat: "Alexandria" },
  { name: "Faribault", population: 13653, region: "South Central", countySeat: "Blue Earth" },
  { name: "Fillmore", population: 21067, region: "Southeast", countySeat: "Preston" },
  { name: "Freeborn", population: 30281, region: "South Central", countySeat: "Albert Lea" },
  { name: "Goodhue", population: 46340, region: "Southeast", countySeat: "Red Wing" },
  { name: "Grant", population: 5972, region: "West Central", countySeat: "Elbow Lake" },
  { name: "Hennepin", population: 1281565, region: "Twin Cities Metro", countySeat: "Minneapolis", notes: "Largest county, pilot for investigation" },
  { name: "Houston", population: 18843, region: "Southeast", countySeat: "Caledonia" },
  { name: "Hubbard", population: 21491, region: "Central", countySeat: "Park Rapids" },
  { name: "Isanti", population: 41000, region: "Twin Cities Metro", countySeat: "Cambridge" },
  { name: "Itasca", population: 45130, region: "Northeast", countySeat: "Grand Rapids" },
  { name: "Jackson", population: 10073, region: "Southwest", countySeat: "Jackson" },
  { name: "Kanabec", population: 16337, region: "Central", countySeat: "Mora" },
  { name: "Kandiyohi", population: 43199, region: "West Central", countySeat: "Willmar" },
  { name: "Kittson", population: 4298, region: "Northwest", countySeat: "Hallock" },
  { name: "Koochiching", population: 12229, region: "Northeast", countySeat: "International Falls" },
  { name: "Lac qui Parle", population: 6623, region: "West Central", countySeat: "Madison" },
  { name: "Lake", population: 10571, region: "Northeast", countySeat: "Two Harbors" },
  { name: "Lake of the Woods", population: 3764, region: "Northwest", countySeat: "Baudette" },
  { name: "Le Sueur", population: 28887, region: "South Central", countySeat: "Le Center" },
  { name: "Lincoln", population: 5639, region: "Southwest", countySeat: "Ivanhoe" },
  { name: "Lyon", population: 25474, region: "Southwest", countySeat: "Marshall" },
  { name: "Mahnomen", population: 5527, region: "Northwest", countySeat: "Mahnomen" },
  { name: "Marshall", population: 9393, region: "Northwest", countySeat: "Warren" },
  { name: "Martin", population: 19683, region: "South Central", countySeat: "Fairmont" },
  { name: "McLeod", population: 35893, region: "South Central", countySeat: "Glencoe" },
  { name: "Meeker", population: 23222, region: "Central", countySeat: "Litchfield" },
  { name: "Mille Lacs", population: 26277, region: "Central", countySeat: "Milaca" },
  { name: "Morrison", population: 33386, region: "Central", countySeat: "Little Falls" },
  { name: "Mower", population: 40062, region: "Southeast", countySeat: "Austin" },
  { name: "Murray", population: 8194, region: "Southwest", countySeat: "Slayton" },
  { name: "Nicollet", population: 34274, region: "South Central", countySeat: "St. Peter" },
  { name: "Nobles", population: 21629, region: "Southwest", countySeat: "Worthington" },
  { name: "Norman", population: 6470, region: "Northwest", countySeat: "Ada" },
  { name: "Olmsted", population: 162847, region: "Southeast", countySeat: "Rochester" },
  { name: "Otter Tail", population: 58746, region: "West Central", countySeat: "Fergus Falls" },
  { name: "Pennington", population: 14119, region: "Northwest", countySeat: "Thief River Falls" },
  { name: "Pine", population: 29579, region: "Central", countySeat: "Pine City" },
  { name: "Pipestone", population: 9126, region: "Southwest", countySeat: "Pipestone" },
  { name: "Polk", population: 31364, region: "Northwest", countySeat: "Crookston" },
  { name: "Pope", population: 11249, region: "West Central", countySeat: "Glenwood" },
  { name: "Ramsey", population: 552352, region: "Twin Cities Metro", countySeat: "Saint Paul", notes: "Second largest, includes St. Paul" },
  { name: "Red Lake", population: 4055, region: "Northwest", countySeat: "Red Lake Falls" },
  { name: "Redwood", population: 15170, region: "Southwest", countySeat: "Redwood Falls" },
  { name: "Renville", population: 14548, region: "South Central", countySeat: "Olivia" },
  { name: "Rice", population: 66972, region: "South Central", countySeat: "Faribault" },
  { name: "Rock", population: 9315, region: "Southwest", countySeat: "Luverne" },
  { name: "Roseau", population: 15165, region: "Northwest", countySeat: "Roseau" },
  { name: "Scott", population: 150928, region: "Twin Cities Metro", countySeat: "Shakopee" },
  { name: "Sherburne", population: 97238, region: "Twin Cities Metro", countySeat: "Elk River" },
  { name: "Sibley", population: 14912, region: "South Central", countySeat: "Gaylord" },
  { name: "St. Louis", population: 200080, region: "Northeast", countySeat: "Duluth", notes: "Includes Duluth" },
  { name: "Stearns", population: 161075, region: "Central", countySeat: "St. Cloud" },
  { name: "Steele", population: 36649, region: "South Central", countySeat: "Owatonna" },
  { name: "Stevens", population: 9805, region: "West Central", countySeat: "Morris" },
  { name: "Swift", population: 9783, region: "West Central", countySeat: "Benson" },
  { name: "Todd", population: 25149, region: "Central", countySeat: "Long Prairie" },
  { name: "Traverse", population: 3259, region: "West Central", countySeat: "Wheaton" },
  { name: "Wabasha", population: 21627, region: "Southeast", countySeat: "Wabasha" },
  { name: "Wadena", population: 13885, region: "Central", countySeat: "Wadena" },
  { name: "Waseca", population: 18612, region: "South Central", countySeat: "Waseca" },
  { name: "Washington", population: 267568, region: "Twin Cities Metro", countySeat: "Stillwater" },
  { name: "Watonwan", population: 10748, region: "South Central", countySeat: "St. James" },
  { name: "Wilkin", population: 6269, region: "West Central", countySeat: "Breckenridge" },
  { name: "Winona", population: 49671, region: "Southeast", countySeat: "Winona" },
  { name: "Wright", population: 141337, region: "Twin Cities Metro", countySeat: "Buffalo" },
  { name: "Yellow Medicine", population: 9709, region: "Southwest", countySeat: "Granite Falls" }
];

export default MINNESOTA_COUNTIES;
